# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/yanni/DSPDude/modules/akm4396/serial_comms/serial_comms.cache/wt [current_project]
set_property parent.project_path /home/yanni/DSPDude/modules/akm4396/serial_comms/serial_comms.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib /home/yanni/DSPDude/modules/akm4396/serial_comms/serial_comms.srcs/sources_1/new/serialcontroller.v
synth_design -top serialcontroller -part xc7a100tcsg324-3
write_checkpoint -noxdef serialcontroller.dcp
catch { report_utilization -file serialcontroller_utilization_synth.rpt -pb serialcontroller_utilization_synth.pb }
