# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yanni/DSPDude/modules/clockgen/clockgen.srcs/sources_1/ip/clkgen1/clkgen1.xci
# IP: The module: 'clkgen1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yanni/DSPDude/modules/clockgen/clockgen.srcs/sources_1/ip/clkgen1/clkgen1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkgen1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/yanni/DSPDude/modules/clockgen/clockgen.srcs/sources_1/ip/clkgen1/clkgen1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkgen1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/yanni/DSPDude/modules/clockgen/clockgen.srcs/sources_1/ip/clkgen1/clkgen1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkgen1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/yanni/DSPDude/modules/clockgen/clockgen.srcs/sources_1/ip/clkgen1/clkgen1.xci
# IP: The module: 'clkgen1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yanni/DSPDude/modules/clockgen/clockgen.srcs/sources_1/ip/clkgen1/clkgen1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkgen1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/yanni/DSPDude/modules/clockgen/clockgen.srcs/sources_1/ip/clkgen1/clkgen1.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkgen1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/yanni/DSPDude/modules/clockgen/clockgen.srcs/sources_1/ip/clkgen1/clkgen1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkgen1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
