# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Valentina/Documents/School/6.111/Final Project/DSPDude/modules/akm4117/settingscontroller/settingscontroller.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Valentina/Documents/School/6.111/Final Project/DSPDude/modules/akm4117/settingscontroller/settingscontroller.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {{C:/Users/Valentina/Documents/School/6.111/Final Project/DSPDude/modules/akm4117/settingscontroller/settingscontroller.srcs/sources_1/imports/new/akm4117settingscontroller.v}}
synth_design -top akm4117settingscontroller -part xc7k70tfbv676-1
write_checkpoint -noxdef akm4117settingscontroller.dcp
catch { report_utilization -file akm4117settingscontroller_utilization_synth.rpt -pb akm4117settingscontroller_utilization_synth.pb }
