# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/yanni/DSPDude/modules/clockgen/clockgen.srcs/sources_1/ip/clkgen2/clkgen2.xci
# IP: The module: 'clkgen2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yanni/DSPDude/modules/clockgen/clockgen.srcs/sources_1/ip/clkgen2/clkgen2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkgen2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/yanni/DSPDude/modules/clockgen/clockgen.srcs/sources_1/ip/clkgen2/clkgen2.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkgen2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/yanni/DSPDude/modules/clockgen/clockgen.srcs/sources_1/ip/clkgen2/clkgen2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkgen2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/yanni/DSPDude/modules/clockgen/clockgen.srcs/sources_1/ip/clkgen2/clkgen2.xci
# IP: The module: 'clkgen2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/yanni/DSPDude/modules/clockgen/clockgen.srcs/sources_1/ip/clkgen2/clkgen2_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkgen2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/yanni/DSPDude/modules/clockgen/clockgen.srcs/sources_1/ip/clkgen2/clkgen2.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkgen2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/yanni/DSPDude/modules/clockgen/clockgen.srcs/sources_1/ip/clkgen2/clkgen2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkgen2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
